=== SeifOSallam/ITI_XML/Lab_1/libraryDTD.dtd
<!DOCTYPE library [
    <!ELEMENT library (location, description, librarian, books)>
    <!ELEMENT location (#PCDATA)>
    <!ELEMENT description (#PCDATA)>
    <!ELEMENT librarian (#PCDATA)>
    <!ELEMENT books (book*)>
    <!ELEMENT book (title, author, preface, parts)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT preface (#PCDATA)>
    <!ELEMENT parts (part+)>
    <!ELEMENT part (chapters)>
    <!ELEMENT chapters (chapter+)>
    <!ELEMENT chapter (summary, sections)>
    <!ELEMENT sections (section+)>
    <!ELEMENT section (content)>
    <!ELEMENT content (#PCDATA)>

    <!ATTLIST book ISBN CDATA #REQUIRED>
    <!ATTLIST part title CDATA #REQUIRED>
    <!ATTLIST chapter title CDATA #REQUIRED>

    <!ENTITY bookContent SYSTEM "bookcontent.txt">
]>

=== SeifOSallam/ITI_XML/Lab_1/library.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE library SYSTEM "libraryDTD.dtd">

<library>
    <location>Cairo</location>
    <description>HELLO WORLD</description>
    <librarian>Seif</librarian>
    <books>
        <book ISBN="1">
            <title>MY WORLD</title>
            <author>Seif</author>
            <preface>OK</preface>
            <parts>
                <part title="Intro">
                    <chapters>
                        <chapter title="The king">
                            <summary>lorem ipsum</summary>
                            <sections>
                                <section>
                                    <content> &bookContent; </content>
                                </section>

                                <section>
                                    <content>lorem ipsum</content>
                                </section>
                            </sections>
                        </chapter>
                    </chapters>
                </part>

                <![CDATA[]]>

                <![CDATA[
                    HELLO THERE, THIS IS SOME CDATA
                ]]>

                <part title="Outro">
                    <chapters>
                        <chapter title="The Jack">
                            <summary>lorem ipsum</summary>
                            <sections>
                                <section>
                                    <content>lorem ipsum</content>
                                </section>

                                <section>
                                    <content>lorem ipsum</content>
                                </section>
                            </sections>
                        </chapter>
                    </chapters>
                </part>
            </parts>
        </book>

        <book ISBN="2">
            <title>MY WORLD</title>
            <author>Seif</author>
            <preface>OK</preface>
            <parts>
                <part title="Whole">
                    <chapters>
                        <chapter title="The Universe">
                            <summary>lorem ipsum</summary>
                            <sections>
                                <section>
                                    <content>lorem ipsum</content>
                                </section>
                            </sections>
                        </chapter>
                    </chapters>
                </part>
            </parts>
        </book>

    </books>
</library>

<book>
    <id>1</id>
    <name>lulu</name>

</book>
